[config.wallpaper]
version_check = false
command = "swww"

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

#[templates.wezterm]
#input_path = '~/.config/matugen/templates/wezterm_theme.toml'
#output_path = '~/.config/wezterm/colors/matugen_theme.toml'
#post_hook = 'touch ~/.config/wezterm/wezterm.lua'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.cava]
input_path = '~/.config/matugen/templates/matugen-cava'
output_path = '~/.config/cava/config'
post_hook = "pkill -USR1 cava"

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.mako]
input_path  = "~/.config/matugen/templates/mako.txt"
output_path = "~/.config/mako/config"
post_hook   = "makoctl reload"

[templates.anyrun]
input_path  = "~/.config/matugen/templates/anyrun.style.css.j2"
output_path = "~/.config/anyrun/style.css"

[templates.yazi]
input_path  = "~/.config/matugen/templates/yazi-theme.toml"
output_path = "~/.config/yazi/theme.toml"


