# : Manager [[[

[mgr]
cwd = { fg = "#efdee0" }

# Tab
tab_active = { fg = "#561d2b", bg = "#ffb1bf", bold = true }
tab_inactive = { fg = "#ffd9de", bg = "#3a0717" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffa855", bg = "#ffa855" }
marker_cut = { fg = "#ffdcbb", bg = "#ffdcbb" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ebbe90", bg = "#ebbe90" }

# Count
count_copied = { fg = "#2c1700", bg = "#ffdcbb" }
count_cut = { fg = "#2c1700", bg = "#ffdcbb" }
count_selected = { fg = "#561d2b", bg = "#ebbe90" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb1bf" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#561d2b", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb1bf", fg = "#561d2b", bold = true }
normal_alt  = { bg = "#524345", fg = "#d6c2c4" }

# Select mode
select_main = { bg = "#e4bdc2", fg = "#43292e", bold = true }
select_alt  = { bg = "#524345", fg = "#d6c2c4" }

# Unset mode
unset_main = { bg = "#ebbe90", fg = "#462a08", bold = true }
unset_alt  = { bg = "#524345", fg = "#d6c2c4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb1bf", bg = "#413738" }
progress_error = { fg = "#ffb4ab", bg = "#413738" }

# Permissions
permissions_t = { fg = "#b8505e" }
permissions_w = { fg = "#bf7223" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff8d22" }
permissions_s = { fg = "#ff4059" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb1bf" }
active = { fg = "#ebbe90", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb1bf" }
value = { fg = "#efdee0" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffb1bf", bold = true, bg = "#191113" }
inactive = { fg = "#e4bdc2", bg = "#191113" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb1bf", bg = "#561d2b" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb1bf" }
title = {}
hovered = { fg = "#ffdcbb", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413738" }
cand = { fg = "#ffb1bf" }
rest = { fg = "#561d2b" }
desc = { fg = "#efdee0" }
separator = " ‚ñ∂ "
separator_style = { fg = "#efdee0" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#efdee0" }
run = { fg = "#efdee0" }
footer = { fg = "#43292e", bg = "#e4bdc2" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ebbe90" }
title_warn = { fg = "#ffb1bf" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#efdee0" },
    { name = "*/", fg = "#ffb1bf" },
]

# : ]]]
