# : Manager [[[

[mgr]
cwd = { fg = "#ebdfe6" }

# Tab
tab_active = { fg = "#4a204b", bg = "#eeb4e9", bold = true }
tab_inactive = { fg = "#ffd6f9", bg = "#320935" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff866c", bg = "#ff866c" }
marker_cut = { fg = "#ffdad2", bg = "#ffdad2" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f6b8aa", bg = "#f6b8aa" }

# Count
count_copied = { fg = "#33110a", bg = "#ffdad2" }
count_cut = { fg = "#33110a", bg = "#ffdad2" }
count_selected = { fg = "#4a204b", bg = "#f6b8aa" }

# Border
border_symbol = " "
border_style  = { fg = "#eeb4e9" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#4a204b", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#eeb4e9", fg = "#4a204b", bold = true }
normal_alt  = { bg = "#4d444b", fg = "#d1c3cc" }

# Select mode
select_main = { bg = "#d9bfd4", fg = "#3c2b3b", bold = true }
select_alt  = { bg = "#4d444b", fg = "#d1c3cc" }

# Unset mode
unset_main = { bg = "#f6b8aa", fg = "#4c261d", bold = true }
unset_alt  = { bg = "#4d444b", fg = "#d1c3cc" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#eeb4e9", bg = "#3e373c" }
progress_error = { fg = "#ffb4ab", bg = "#3e373c" }

# Permissions
permissions_t = { fg = "#a05f94" }
permissions_w = { fg = "#e74420" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff5c39" }
permissions_s = { fg = "#ff3de3" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#eeb4e9" }
active = { fg = "#f6b8aa", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#eeb4e9" }
value = { fg = "#ebdfe6" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#eeb4e9", bold = true, bg = "#171216" }
inactive = { fg = "#d9bfd4", bg = "#171216" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#eeb4e9", bg = "#4a204b" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#eeb4e9" }
title = {}
hovered = { fg = "#ffdad2", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3e373c" }
cand = { fg = "#eeb4e9" }
rest = { fg = "#4a204b" }
desc = { fg = "#ebdfe6" }
separator = " ‚ñ∂ "
separator_style = { fg = "#ebdfe6" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ebdfe6" }
run = { fg = "#ebdfe6" }
footer = { fg = "#3c2b3b", bg = "#d9bfd4" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#f6b8aa" }
title_warn = { fg = "#eeb4e9" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#ebdfe6" },
    { name = "*/", fg = "#eeb4e9" },
]

# : ]]]
