# : Manager [[[

[mgr]
cwd = { fg = "#f1dedc" }

# Tab
tab_active = { fg = "#571e1b", bg = "#ffb3ad", bold = true }
tab_inactive = { fg = "#ffdad6", bg = "#3b0908" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#fdb941", bg = "#fdb941" }
marker_cut = { fg = "#fedea6", bg = "#fedea6" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e1c28c", bg = "#e1c28c" }

# Count
count_copied = { fg = "#261900", bg = "#fedea6" }
count_cut = { fg = "#261900", bg = "#fedea6" }
count_selected = { fg = "#571e1b", bg = "#e1c28c" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb3ad" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#571e1b", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb3ad", fg = "#571e1b", bold = true }
normal_alt  = { bg = "#534342", fg = "#d8c2bf" }

# Select mode
select_main = { bg = "#e7bdb9", fg = "#442927", bold = true }
select_alt  = { bg = "#534342", fg = "#d8c2bf" }

# Unset mode
unset_main = { bg = "#e1c28c", fg = "#402d04", bold = true }
unset_alt  = { bg = "#534342", fg = "#d8c2bf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb3ad", bg = "#423735" }
progress_error = { fg = "#ffb4ab", bg = "#423735" }

# Permissions
permissions_t = { fg = "#c05247" }
permissions_w = { fg = "#a87b2c" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#fca60f" }
permissions_s = { fg = "#ff503d" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb3ad" }
active = { fg = "#e1c28c", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb3ad" }
value = { fg = "#f1dedc" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffb3ad", bold = true, bg = "#1a1110" }
inactive = { fg = "#e7bdb9", bg = "#1a1110" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb3ad", bg = "#571e1b" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb3ad" }
title = {}
hovered = { fg = "#fedea6", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#423735" }
cand = { fg = "#ffb3ad" }
rest = { fg = "#571e1b" }
desc = { fg = "#f1dedc" }
separator = " ‚ñ∂ "
separator_style = { fg = "#f1dedc" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f1dedc" }
run = { fg = "#f1dedc" }
footer = { fg = "#442927", bg = "#e7bdb9" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e1c28c" }
title_warn = { fg = "#ffb3ad" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f1dedc" },
    { name = "*/", fg = "#ffb3ad" },
]

# : ]]]
