# : Manager [[[

[mgr]
cwd = { fg = "#dee3e6" }

# Tab
tab_active = { fg = "#003642", bg = "#86d1e9", bold = true }
tab_inactive = { fg = "#b1ebff", bg = "#001f27" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#797dff", bg = "#797dff" }
marker_cut = { fg = "#dfe0ff", bg = "#dfe0ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#c1c4eb", bg = "#c1c4eb" }

# Count
count_copied = { fg = "#151937", bg = "#dfe0ff" }
count_cut = { fg = "#151937", bg = "#dfe0ff" }
count_selected = { fg = "#003642", bg = "#c1c4eb" }

# Border
border_symbol = " "
border_style  = { fg = "#86d1e9" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003642", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#86d1e9", fg = "#003642", bold = true }
normal_alt  = { bg = "#40484b", fg = "#bfc8cc" }

# Select mode
select_main = { bg = "#b2cad3", fg = "#1d343b", bold = true }
select_alt  = { bg = "#40484b", fg = "#bfc8cc" }

# Unset mode
unset_main = { bg = "#c1c4eb", fg = "#2a2e4d", bold = true }
unset_alt  = { bg = "#40484b", fg = "#bfc8cc" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#86d1e9", bg = "#343a3c" }
progress_error = { fg = "#ffb4ab", bg = "#343a3c" }

# Permissions
permissions_t = { fg = "#568596" }
permissions_w = { fg = "#4d56c6" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#464cff" }
permissions_s = { fg = "#18c4ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#86d1e9" }
active = { fg = "#c1c4eb", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#86d1e9" }
value = { fg = "#dee3e6" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#86d1e9", bold = true, bg = "#0f1416" }
inactive = { fg = "#b2cad3", bg = "#0f1416" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#86d1e9", bg = "#003642" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#86d1e9" }
title = {}
hovered = { fg = "#dfe0ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343a3c" }
cand = { fg = "#86d1e9" }
rest = { fg = "#003642" }
desc = { fg = "#dee3e6" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dee3e6" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee3e6" }
run = { fg = "#dee3e6" }
footer = { fg = "#1d343b", bg = "#b2cad3" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#c1c4eb" }
title_warn = { fg = "#86d1e9" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dee3e6" },
    { name = "*/", fg = "#86d1e9" },
]

# : ]]]
