[general]
import = ["colors.toml"]

[window]
opacity = 0.8
padding = { x = 10, y = 10 }

[font]
size = 12.0  # 字体大小

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"
