[colors.primary]
background = '#191113'
foreground = '#efdee0'
 
[colors.cursor]
text = '#efdee0'
cursor = '#d6c2c4' 
 
[colors.vi_mode_cursor]
text = '#191113'
cursor = '#ffb1c2' 
 
[colors.search.matches]
foreground = '#524346' 
background = '#ecbe91' 
 
[colors.search.focused_match]
foreground = '#524346' 
background = '#ffb1c2' 
 
[colors.footer_bar]
foreground = '#524346' 
background = '#efdee0' 
 
[colors.hints.start]
foreground = '#524346' 
background = '#e4bdc4' 
 
[colors.hints.end]
foreground = '#524346' 
background = '#e4bdc4' 
 
[colors.selection]
text = '#191113'
background = '#ffb1c2'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb1c2' 
yellow = '#8d4a5a' 
blue = '#ffb1c2' 
magenta = '#ecbe91' 
cyan = '#e4bdc4' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
